### ISSUE TITLE
px-data-table does not display leading and trailing whitespace of data field

### ISSUE THREAD

**Issue by genausad** [predixdesignsystem/px-data-table#106]
Hi,
We have a usecases to display spaces of field on px-data-table but by default px-data-table remove leading and trailing whitespace of field on px-data-table.

**Expected behavior and actual behavior:** 
We have a below data from postgress db in Json format
![data](https://cloud.githubusercontent.com/assets/26219864/23610471/a26e2410-0298-11e7-9ade-dbd3f4c7c4ef.jpg)

**Expected behavior:** When we display above data on px-data-table then we should able to see data as it is on px-data-table. Spaces in fileName and notes fields value should be displayed on px-data-table.  
![expected-behavior](https://cloud.githubusercontent.com/assets/26219864/23610233/d932c614-0297-11e7-8631-66f3229f68b6.jpg)

**Actual behavior:** When we display above data on px-data-table then we are not able to see data as it is on px-data-table.By default px-data-table remove leading and trailing whitespace of field on px-data-table.
![actual-behavior](https://cloud.githubusercontent.com/assets/26219864/23610322/0d965a60-0298-11e7-90fa-681e3875ce54.jpg)

**Steps to reproduce the problem:**
Save some data in postgress db with leading and trailing whitespace in string and then try to display that data on px-data-table. We will see, leading and trailing whitespace will be removed from data fields on px-data-table.
**Environment:**
px-data-table components version - 1.14.0,
Windows 7, 
browser - Chrome & IE

**Comment by mdwragg** [comment]
Closing due to age and release of https://www.predix-ui.com/#/elements/data-grid/px-data-grid
