### ISSUE TITLE
px-data-table goes back to page 1 if edit made on page number other than 1

### ISSUE THREAD

**Issue by jcheenatcode** [predixdesignsystem/px-data-table#130]
* Didn't find existing issues

## Expected behavior and actual behavior:
We are not sure what the expected behavior of px-data-table, but we were expecting that if an edit is made on any page other than page 1 it should stay on that page.

## Steps to reproduce the problem:

1. Open Codepen: https://codepen.io/anon/pen/NjXdPB?editors=1001
2. Go to page 3
3. Edit a value
4. Go out of focus, so that the value is stored
5. This should automatically take you to page 1

## Environment (_component version number, Browser (including version), operating system, hardware, etc_):
Chrome
Windows 7
i7
16GB Ram

## Code examples help us better understand the issue - follow the appropriate codepen for the Codepen: https://codepen.io/anon/pen/NjXdPB?editors=1001

**Comment by randyaskin** [comment]
I agree that it probably makes sense to remain on the same page of records.

@mdwragg if I comment out this line of code, the table remains on the same page but the edit functionality still works. Any chance you remember why you put that notifyPath in? I know it was a year ago. :) https://github.com/PredixDev/px-data-table/blob/master/aha-table.html#L961

**Comment by kentcabarle** [comment]
@randyaskin Any fix for this one? I tried commenting out the notify-path in _saveData() but it seems like it's still going to page 1 after edit. :(

**Comment by mdwragg** [comment]
Closing due to age and release of https://www.predix-ui.com/#/elements/data-grid/px-data-grid
