### ISSUE TITLE
px-data-table-column value wrap with html tag

### ISSUE THREAD

**Issue by amankumarshaw** [predixdesignsystem/px-data-table#132]
we want to wrap the px-data-table-column value with html tags
e.g 

```
<px-data-table-column name="id" type="html" value="<button>{{id.value}}</button>" label="Remove">
</px-data-table-column>
```

So that we no need to update the value with html tags in json array.

Can we do something like that, if yes please let me know the syntax with snippet.

**Comment by randyaskin** [comment]
Could be similar to, or handled by, #92

**Comment by mdwragg** [comment]
Closing due to age and release of https://www.predix-ui.com/#/elements/data-grid/px-data-grid
