### ISSUE TITLE
Tab, enter, arrow navigate in Predix Data Tables

### ISSUE THREAD

**Issue by tompabst** [predixdesignsystem/px-data-table#133]
Need to have the ability to navigate the cells in the data table with Tab, Enter, and Arrow Keys (the same as in an excel table). This will allow digital measurements tools to be used on the shop floor in conjunction with the Predix applications using the data tables. Without the navigation the operator on the shop floor has to take a measurement and return to the screen in between each data point. This can add hours to an inspection process where we have hundreds of inscription points. 

![image](https://cloud.githubusercontent.com/assets/28811236/26256964/bd7ca6f4-3c8c-11e7-8f98-5449576fe6bf.png)

**Comment by mdwragg** [comment]
Closing due to age and release of https://www.predix-ui.com/#/elements/data-grid/px-data-grid
