### ISSUE TITLE
Adding DatePicker option on edit & Drilldown option in table row

### ISSUE THREAD

**Issue by bhatankit** [predixdesignsystem/px-data-table#135]
Is there any way we can add datepicker option on edit to select a date?

Also we have a scenario to drilldown data by multiple levels in data table?

I have added screenshots for the same,
**DatePicker Editable field:**
![image](https://cloud.githubusercontent.com/assets/18552272/26400688/e3f43542-409f-11e7-9166-ea6861de16ba.png)

**Drilldown data:**

![image](https://cloud.githubusercontent.com/assets/18552272/26400649/adf66cee-409f-11e7-8859-fc493e4ff0d9.png)

**Comment by mdwragg** [comment]
Closing due to age and release of https://www.predix-ui.com/#/elements/data-grid/px-data-grid
