### ISSUE TITLE
fix table header

### ISSUE THREAD

**Issue by amankumarshaw** [predixdesignsystem/px-data-table#137]
How to fix table header with scrollable table body in px-data-table ?

**Comment by randyaskin** [comment]
See also PR #117

**Comment by mdwragg** [comment]
Closing due to age and release of https://www.predix-ui.com/#/elements/data-grid/px-data-grid

**Comment by mdwragg** [comment]
Closing due to age and release of https://www.predix-ui.com/#/elements/data-grid/px-data-grid
