### ISSUE TITLE
px-data-table-column hide property leaves column heading

### ISSUE THREAD

**Issue by kornfein** [predixdesignsystem/px-data-table#143]
Using px-data-table-column hide property to not display a column in certain situations. The hide property removes the data in the table but leaves the column header which is rather confusing, seems like a bug.

Saw some other issues around the hide property but not this one, I am on version 3.0.2

**Comment by kornfein** [comment]
BTW is am on version 3.0.2

**Comment by mdwragg** [comment]
Closing due to age and release of https://www.predix-ui.com/#/elements/data-grid/px-data-grid
