### ISSUE TITLE
FF: column reorder doesn't work

### ISSUE THREAD

**Issue by randyaskin** [predixdesignsystem/px-data-table#144]
### Submit an Issue

Someone pointed out on the forums that the `enable-column-reorder` property doesn't seem to work in Firefox.
https://forum.predix.io/questions/24638/px-data-table-the-option-enable-column-reorder-doe.html

### Steps to reproduce the problem:
Will have to run locally or use CodePen, since column reordering is not included in the interactive demo page by default.

### Environment (_component version number, Browser (including version), operating system, hardware, etc_):
Firefox v54

### Code examples help us better understand the issue.
https://codepen.io/randyaskin/pen/NgBEXY?&editors=1001

**Comment by mdwragg** [comment]
Closing due to age and release of https://www.predix-ui.com/#/elements/data-grid/px-data-grid
