### ISSUE TITLE
Allow programmaticly selecting a row in a px-data-table

### ISSUE THREAD

**Issue by kornfein** [predixdesignsystem/px-data-table#148]
Based on forum response it is not possible to do this today, seems like something that should be there.

**Comment by richardpineo** [comment]
I ran into this need today as well. Will likely switch to using:
https://vaadin.com/elements/vaadin-grid
or a different control due to this need.

**Comment by mdwragg** [comment]
Closing due to age and release of https://www.predix-ui.com/#/elements/data-grid/px-data-grid
