### ISSUE TITLE
Table column header was not updated when update table data

### ISSUE THREAD

**Issue by nguyenlk** [predixdesignsystem/px-data-table#161]
When I change data by removing 1 property, header of table did not disappear.

Example:
firstData = [
            {'first': 'Valentine', 'last': 'Meyer', 'email': 'valentinemeyer@scentric.com'},
            {'first': 'Silva', 'last': 'Alexander', 'email': 'silvaalexander@gmail.com'},
            {'first': 'Hopkins', 'last': 'Wong', 'email': 'hopkinswong@hotmail.com'},
            {'first': 'Joe', 'last': 'Sherman', 'email': 'joejoe@yahoo.com'},
            {'first': 'Jane', 'last': 'Bartlett', 'email': 'jane@scentric.com'}];

secondData = [
            {'first': 'Valentine', 'last': 'Meyer'},
            {'first': 'Silva', 'last': 'Alexander'},
            {'first': 'Hopkins', 'last': 'Wong'},
            {'first': 'Joe', 'last': 'Sherman'},
            {'first': 'Jane', 'last': 'Bartlett'}];
![data-table-error](https://user-images.githubusercontent.com/8244750/31213960-3ee89bc2-a9d3-11e7-9397-5b4897bb95ce.PNG)

Please help me check this issue.
Thanks

**Comment by randyaskin** [comment]
Are you defining columns with `<px-data-table-column>` definitions? Or relying on the `includeAllColumns` property to auto-define the columns? When you change from firstData to secondData are you using the proper Polymer syntax for an array property? e.g. `myTable.set('tableData', secondData)` as opposed to `myTable.tableData = secondData`?

**Comment by gefuxu** [comment]
mute the thread

Sent from my iPad

在 2017年10月6日，01:06，Randy Askin <notifications@github.com<mailto:notifications@github.com>> 写道：


Are you defining columns with <px-data-table-column> definitions? Or relying on the includeAllColumns property to auto-define the columns? When you change from firstData to secondData are you using the proper Polymer syntax for an array property? e.g. myTable.set('tableData', secondData) as opposed to myTable.tableData = secondData?

**Comment by nguyenlk** [comment]
I tried:
- Add/remove includeAllColumns property
- Use myTable.set('tableData', secondData) and myTable.tableData = secondData

but header isn't updated.

**Comment by mdwragg** [comment]
Closing due to age and release of https://www.predix-ui.com/#/elements/data-grid/px-data-grid
