### ISSUE TITLE
Edit field different size than table column

### ISSUE THREAD

**Issue by vbashorunge** [predixdesignsystem/px-data-table#172]
## Expected behavior and actual behavior:
Expected behavior: when clicking on a cell to edit textual data, the edit field is the same width/size as the original cell

Actual behavior:
edit field is different size (usually smaller) than the original cell

## Steps to reproduce the problem:
Enter text data into any field on a row in order to make the table stretch

Once you see sufficient table stretching, click out, then click back into the cell to edit.

You'll now see the edit field is the same size as the original cell before stretching, and the table "snaps" back to accommodate this.

## Environment (_component version number, Browser (including version), operating system, hardware, etc_):

Component Version Number: 5.0.4

Browser: Google Chrome Ver. 61.0.3163.100 64-bit

OS: "OS X El Capitan" (10.11.6)

Hardware: Macbook Pro - Retina 15" - 2.5Ghz Intel Core i7

**Comment by mdwragg** [comment]
Closing due to age and release of https://www.predix-ui.com/#/elements/data-grid/px-data-grid
