### ISSUE TITLE
px-data-table not able to mark checkbox as checked, when user back with his selected Items

### ISSUE THREAD

**Issue by shashidharBM** [predixdesignsystem/px-data-table#175]
# Submit an Issue

Hi,

Thanks for helping us improve the Predix UI platform by submitting an issue.

Before you begin, please check the list of existing issues to avoid submitting a duplicate issue.

To help us solve this issue as fast as possible, please fill out the following sections:

##Already Selected items from API Need to be shown as checkbox checked and Not able to achieve  with the selectedRows property as it's readonly. And wrote some DOM selection related function to select and check. But this is working only if, you have selected item appears in first 10 rows(or first page) Not working on Pagination or Column filters

## At least we need one event handler to identify user clicked on Pagination/pagenumber option.
So if we identified the user action, then we are good to call above DOM manipulation method.

##  
const selectedProjects = this.querySelectorAll('#myDataTable aha-table .rows');
       const savedProjects = this.savedStoredProjectIds.split(',');
       for (let l = 0; l < selectedProjects.length; l++) {
         const parentElem = selectedProjects[l];
         const firstSibling = parentElem.querySelectorAll('px-data-table-cell span')[1].innerText;
         for (let m = 0; m < savedProjects.length; m++) {
           if (firstSibling === savedProjects[m]) {
             parentElem.querySelectorAll('[role="checkbox"]')[0].click();
           }
         }
       }

## with SelectedRows (read Only property of px-data-table component)
       const savedProjects = this.savedStoredProjectIds.split(',');
       const projects = this.querySelector('#myDataTable aha-table').displayedRows;
       for(let k = 0; k < projects.length; k++) {
         const elem = projects[k];
         for (let m = 0; m < savedProjects.length; m++) {
           if (elem.row.project.value === savedProjects[m]) {
             this.push('selectedProjectsRows', elem)     
           }
       }
       }

**Comment by mdwragg** [comment]
Closing due to age and release of https://www.predix-ui.com/#/elements/data-grid/px-data-grid
