### ISSUE TITLE
Filter Missing from Columns that are Initially Hidden

### ISSUE THREAD

**Issue by jonkishkunasge** [predixdesignsystem/px-data-table#178]
## Expected behavior and actual behavior:
Expected: A column that is initially hidden ("hide" attribute present in DOM when created) will show its filter box when picked via the column chooser.
Actual: A column that is initially hidden ("hide" attribute present in DOM when created) has no filter box when picked via the column chooser. Note that this used to work (worked in pre-refresh, though unsure whether the refresh itself was related).

## Steps to reproduce the problem:
Create a complex table type with one or more columns that are initially hidden - "hide" attribute in DOM. Use the column chooser to show the column. Example code snippet:

```
<px-data-table
	page-size="20"
	striped
	enable-column-resize
	enable-column-reorder
	table-cells
	table-columns
	show-column-chooser filterable sortable>

	<px-data-table-column name="displayName" label="Tag" filterable sortable ></px-data-table-column>
	<px-data-table-column name="tagNameInFeed" label="Source Tag" filterable sortable></px-data-table-column>
	<px-data-table-column name="decimals" label="Decimals" filterable sortable hide></px-data-table-column>
</px-data-table>
```

## Environment:
Chrome 61.0.3163.100
Windows 7

## Screenshots:
Arrows point to columns added via the column chooser:
![image](https://user-images.githubusercontent.com/13875331/32744929-d03ef8c0-c876-11e7-9ee5-650e76bcd99a.png)

**Comment by mdwragg** [comment]
Closing due to age and release of https://www.predix-ui.com/#/elements/data-grid/px-data-grid
