### ISSUE TITLE
the sorter icon is pushed below the column label when there are more columns

### ISSUE THREAD

**Issue by elvinfucom** [predixdesignsystem/px-data-table#183]
At https://www.predix-ui.com/#/elements/data-table/px-data-table

I tried to add more columns in the TABLE DATA property, then when click column to sort, the sorter icon is pushed below the column label when there are more columns.

**Comment by mdwragg** [comment]
Closing due to age and release of https://www.predix-ui.com/#/elements/data-grid/px-data-grid
