### ISSUE TITLE
Feature Request: Row Collapsible

### ISSUE THREAD

**Issue by 212556430** [predixdesignsystem/px-data-table#185]
# Submit an Issue

Please provide a way to collapse a row to find child under it.

Examples:
https://datatables.net/examples/api/row_details.html
https://saulis.github.io/iron-data-table/demo/details.html
https://vaadin.com/elements/vaadin-grid/html-examples/grid-row-details-demos

**Comment by randyaskin** [comment]
The next version of our data table is actually being built by Vaadin currently based on their grid and will have this functionality. Coming by end of year.

**Comment by mdwragg** [comment]
Closing due to age and release of https://www.predix-ui.com/#/elements/data-grid/px-data-grid
