### ISSUE TITLE
Setting column level filters programatically in client-side model

### ISSUE THREAD

**Issue by LRagji** [predixdesignsystem/px-data-table#187]
# Request for enhancement

## Expected behaviour:
Need functionality(APIs) to be able to set column level filters programatically, currently the only way is via user input in filter textbox 

## Steps to reproduce the problem:
Enable filtering attribute and type into filter text box, No API methods to set filter on the dataset.

**Comment by LRagji** [comment]
Is this a possibility in the near future? if any one can confirm, comment....

**Comment by randyaskin** [comment]
We are not currently investing much effort in the existing px-data-table, as we will be replacing it completely with the Vaadin-based grid in the coming weeks. Their grid already has an API for filtering, so I assume the Predix version will contain something similar, but am not 100% sure.

**Comment by LRagji** [comment]
Any expected date?

**Comment by randyaskin** [comment]
Delivery from Vaadin should happen by the end of the year, but we may need additional time for code review and testing before making the code public.

**Comment by mdwragg** [comment]
Closing due to age and release of https://www.predix-ui.com/#/elements/data-grid/px-data-grid
