### ISSUE TITLE
Not translating numbers according to localization en/fr

### ISSUE THREAD

**Issue by LRagji** [predixdesignsystem/px-data-table#189]
# Submit an Issue
When i am passing tabledata which contains number in the json array decimal points are not translated according to locales. 

## Expected behavior 
Numerals should display 10,7 in fr and 10.7 in en-US locale

##Actual behavior
10.7 in fr and 10.7 in en-US

## Steps to reproduce the problem:
Bind the tabeldata property with following data [{ "length":10.7}]
Set the language property to en-US and then switch to fr
Set the resources property with following data {"en-US":{}"fr":{}}

Have i missed something?

**Comment by mdwragg** [comment]
Closing due to age and release of https://www.predix-ui.com/#/elements/data-grid/px-data-grid
