### ISSUE TITLE
[Localization]Type Drop-down column is selected by val

### ISSUE THREAD

**Issue by LRagji** [predixdesignsystem/px-data-table#190]
If i select px-dropdown as column type the data in it is selected by 'val' and not by 'key' thus not letting localization work as options will change according to the localization language thus not letting tabledata array bind to the column.

## Expected behavior:
px-dropdown to be selected by key and not by val

## Steps to reproduce the problem:
px-data-table-cell.html
` <px-dropdown
              class="px-dropdown-content"
              selected="{{cellValue}}"
              select-by="val"
              display-value="{{cellDisplayValue}}"
              on-px-dropdown-selection-changed="saveCell"
              allow-outside-scroll="true"
              button-style="bare"
              items="{{dropdownItems}}"
              disable-clear>
            </px-dropdown>`

**Comment by mdwragg** [comment]
Closing due to age and release of https://www.predix-ui.com/#/elements/data-grid/px-data-grid
