### ISSUE TITLE
If Select All checkbox is checked, it is getting unchecked with sorting and filtering on any column

### ISSUE THREAD

**Issue by sandhyathakur** [predixdesignsystem/px-data-table#192]
# Submit an Issue

Hi,

Thanks for helping us improve the Predix UI platform by submitting an issue.

Before you begin, please check the list of existing issues to avoid submitting a duplicate issue.

To help us solve this issue as fast as possible, please fill out the following sections:

## Expected behavior and actual behavior:
Expected: Select All should retain its state unless the rows selection is changed
Actual: If Select All is checked and we apply filter or sorting on any column, Select All is getting unchecked.  
## Steps to reproduce the problem:
1. Create a table that is sortable, filterable and selectable.
2. Click Select All Checkbox to select all rows.
3. Sort any column of the table. (Or apply filter to any column)
4. Select All Checkbox is unchecked. (Though all the rows are still selected.)

## Environment (_component version number, Browser (including version), operating system, hardware, etc_):
Component Version Number : v 5.1.7
Browser : Google Chrome Version 63.0.3239.132
Operating System: Windows 7 Professional x64

## Screenshots (_optional, but very helpful_):
Issue can be reproduced at
https://www.predix-ui.com/px-data-table/px-data-table/
Select property sortable, filterable and selectable.
And then follow steps to reproduce.

## Code examples help us better understand the issue - follow the appropriate codepen for the component by going to https://predix-ui.com, finding the component in question, and clicking on the pencil icon under the demo.
        Once you've created your code example, you can save it under a new url.
        Please note that you should NOT use the same methods for production as the ones used in codepen - these methods are not production ready.

**Comment by mdwragg** [comment]
Closing due to age and release of https://www.predix-ui.com/#/elements/data-grid/px-data-grid
