### ISSUE TITLE
Feature Request: Numerical Comparisons in Filters

### ISSUE THREAD

**Issue by gtjohnson1** [predixdesignsystem/px-data-table#193]
We have received requests from multiple customers for the ability to add numerical comparisons in the filter box for columns. Example below: 
There is a column that shows the "occurrence number" of each row, and there are 100 rows. Users want to be able to type ">50" in the filter box to only show rows that have an occurrence greater than 50. This would allow users to quickly filter out rows that they do not wish to see.

**Comment by mdwragg** [comment]
Closing due to age and release of https://www.predix-ui.com/#/elements/data-grid/px-data-grid
