### ISSUE TITLE
Do we have option to make the default first row to be selected

### ISSUE THREAD

**Issue by nraafee** [predixdesignsystem/px-data-table#201]
do we have option to make the default first row to be selected. I am working for OPM application GE Energy. we have some requirement and we need to do lot of customization. the same i have composed mail to David
Hello David,
 
We are using the px-data-table component to load the block and the related assets. Based on the UI Mockup the Block should be selected when the page loads. So is there any property to make the first entry selected.
 
To achieve this I have added a class in css “highlightBlue” and appended to the grid. Once the user clicks on the different asset eg: AC270T932 immediately I am filtering the json data and passing it to the chart it is rendering but I am manually removing the “highlightBlue” class and the selected row got highlighted otherwise it is highlighting both block and asset.
 
cid:image001.png@01D3F287.8E6A3C30
 
When we change the date range then again we are sending a request to the micro services and once we get response then we are binding the gridData it is updating but “selectedRows” property having the previous selected rows, so once the response comes back automatically it is highlighting the previous selected row and the first rows which we are manually making highlighted.
 
cid:image002.png@01D3F287.8E6A3C30
 
We are using the property selectable single-select=true but still we are making the first column with the radio button “display:none” and added event
 
var el = document.getElementById("myDataTable");
if (el) {
  el.addEventListener("px-row-click", function(event) {
  var defaultSelected = document.querySelectorAll("#scrollBodyTableContainer")[1];
  var rowSelected = $(defaultSelected).find('.tr:nth-child(3)');
    var result = (self.trendSeries[0].result).filter(function( obj ) {
      return obj.assetId == event.detail.row.row.assetId.value;
    });
    var chartDom = document.getElementById("trendChart");
    var selectedRowValues = document.getElementById("myDataTable");
    if (result[0]) {
      rowSelected.removeClass('highlightBlue');
    }
    self.degradationData[0].data = result[0].values;
    chartDom._createChart();
    self.isLoadingChart = false;
  });
 
 
sometimes if user click on the row it is not getting clicked. When we click second time then it is getting clicked. Please help us out in fixing the issues.
 
Regards,
Raafee N

**Comment by arongraham-ge** [comment]
this table has been deprecated. please use https://www.predix-ui.com/#/elements/data-grid/px-data-grid
