### ISSUE TITLE
Predix data table header is not working properly on update or delete

### ISSUE THREAD

**Issue by gabrielIps** [predixdesignsystem/px-data-table#51]
# Submit an Issue

Hi,

Thanks for helping us improve the Predix UI platform by submitting an issue.

Before you begin, please check the list of existing issues to avoid submitting a duplicate issue.

To help us solve this issue as fast as possible, please fill out the following sections:
## Expected behavior and actual behavior:

We are you using px-data-table in our application with selectable. when i select any particular column in the table and mark as delete or update it stays selected at the header as(1) even after the table got updated but it has to display as (0) once after the table got refreshed.
[data-table-issue.docx](https://github.com/PredixDev/px-data-table/files/467407/data-table-issue.docx)
## Steps to reproduce the problem:

Use selectable in the px-data-table, select a row in the table it will display as selected (1) in the header but once you delete or update the row it should refresh the data table and it should display as selected(0) instead of (1).
## Environment (_component version number, Browser (including version), operating system, hardware, etc_):

"px-data-table": "~v1.12.3", Chrome browser Version 52.0.2743.116 (64-bit), Predix environment, Mac OS

**Comment by mdwragg** [comment]
Closing due to age and release of https://www.predix-ui.com/#/elements/data-grid/px-data-grid
