### ISSUE TITLE
Column width

### ISSUE THREAD

**Issue by PiotrekPaprocki** [predixdesignsystem/px-data-table#57]
## Expected behavior and actual behavior:

An option to set size (width) to value/percentage/fixed of column would be nice to have. It's really basic thing that is missing from px-table.

If there is such option please correct me.

**Comment by benmak11** [comment]
@mdwragg Just wanted to reach out and find out if this is in queue to be implemented?

**Comment by mdwragg** [comment]
Hi, it is not. We're flat out with other commitments for the near future. Want to help us develop it? :-)

**Comment by benmak11** [comment]
@mdwragg if I have time I will add this to my slate 😃 I am already working on [this](https://github.com/PredixDev/px-data-table/issues/66) feature right now

**Comment by mdwragg** [comment]
Awesome! Can't wait to see it :-)

**Comment by mdwragg** [comment]
Closing due to age and release of https://www.predix-ui.com/#/elements/data-grid/px-data-grid
