### ISSUE TITLE
Row expand and collapse on row click

### ISSUE THREAD

**Issue by krishnathota** [predixdesignsystem/px-data-table#67]
Row details should be available on row click - currently there is neither a row click event nor a row detail view on clicking of one

**Comment by mdwragg** [comment]
Hi, can you help us fix this? We'd love a pull request that fixes your issue!

**Comment by ashleydf** [comment]
I've seen several people asking for this feature. Are you guys going to add it?

**Comment by krishnathota** [comment]
No, not right now. I tried doing that but it needed changes in the core aha table file. Even though we do that, there is an issue. The content that we place inside the expanded row, is being confined to the first column. I was unable to fix that. So we had to use another component.

**Comment by mimen123** [comment]
When will this be added?

**Comment by randyaskin** [comment]
I don't believe we have any plans to implement this functionality right now, though we are looking at making some enhancements to the px-data-table in Q3 after we finish our current release. I'll remind our PM of this request.

As a small correction to @krishnathota 's original comments, we do fire a `px-row-click` event when a row is clicked in the table. The `detail` contains a reference to the row and column that were clicked.

**Comment by mdwragg** [comment]
Closing due to age and release of https://www.predix-ui.com/#/elements/data-grid/px-data-grid
