### ISSUE TITLE
How to Reload the Data Table.

### ISSUE THREAD

**Issue by Ishank-dubey** [predixdesignsystem/px-data-table#80]
When I change the table-data array to a blank array [] , the select all button still remains checked if was checked prior to making the table-data as []. Can this be solved in the data-table implementation? 
What is the way to reload the data-table that as well clears the `Selected (x)` check marks?

**Comment by arnaudLC35** [comment]
I have a very similar issue: if I load some data in a table-data, then select some (or all) row(s), and finally replace the table-data bu other data, the selected rows remain displayed as selected.

As the selectedRows property is read only, forcing it to be emptied do not solve the problem.

Is their a way to clear the selection when updating the data in the table?

Thanks,

**Comment by randyaskin** [comment]
This is still an open issue, but someone has posted a potential workaround on the forums here: http://forum.predix.io/questions/16898/how-to-clear-selections-of-data-table-on-ajax-refr.html

**Comment by mdwragg** [comment]
Closing due to age and release of https://www.predix-ui.com/#/elements/data-grid/px-data-grid
