### ISSUE TITLE
px-data-table-highlight does not work unless px-data-table has selectable property in left most column

### ISSUE THREAD

**Issue by kornfein** [predixdesignsystem/px-data-table#85]
## Expected behavior and actual behavior:
Row or cell should highlight when px-data-table-highlight is added to a column. No highlighting appears , the highlighting does not work unless the selectable attribute is set on the parent
 px-data-table

## Steps to reproduce the problem:
Try using the code snippet  for _px-data-highlight under: https://www.predix-ui.com/?show=px-data-table&type=component_  It does not work!!
## Environment (_component version number, Browser (including version), operating system, hardware, etc_):
Using px-data-table v1.11.1 and verified bug still exists in v1.14.21

## Code examples help us better understand the issue
**Your code snippet right from the example in the Predix UI catalog does not work:**
![px-data-table-highlight](https://cloud.githubusercontent.com/assets/5863663/21188215/a2be46c0-c1e8-11e6-8a1b-13fac7f3cd39.jpg)

**Comment by kornfein** [comment]
Investigated this further it turns out the issue only occurs when the highlighting is for the first column (from the left side), cells in other columns highlight ok whether selectable is set or not. I suspect the reason that selectable allows the first column to be highlighted is that the checkbox is effectively a new left most column.

**Comment by randyaskin** [comment]
Oops, not actually fixed in 2.0.0 - ignore all those ^^^ references :P

**Comment by mdwragg** [comment]
Closing due to age and release of https://www.predix-ui.com/#/elements/data-grid/px-data-grid
