### ISSUE TITLE
Feature Request: Add a rendering function 

### ISSUE THREAD

**Issue by mvelez** [predixdesignsystem/px-data-table#92]
## Expected behavior and actual behavior:

Provide a way to define a function to transform data when rendering.  Common situations when this is needed are when you are dealing with currencies, with JSON that comes back with IDs, and when you want to put an input such as a checkbox on a grid row.

Examples in competitive data-grid products:
https://vaadin.com/docs/-/part/elements/vaadin-grid/vaadin-grid-data-formatting.html
https://datatables.net/examples/advanced_init/column_render.html

**Comment by mdwragg** [comment]
Closing due to age and release of https://www.predix-ui.com/#/elements/data-grid/px-data-grid
