### ISSUE TITLE
Px-data-table-column property "hide" doesn't work

### ISSUE THREAD

**Issue by randyaskin** [predixdesignsystem/px-data-table#94]
### Expected behavior and actual behavior:
If you explicitly define a `<px-data-table-column name="foo" hide="true">` I would expect the column to appear hidden by default, but still show up as an option in the column chooser dropdown. Instead, the column appears anyway. The hide behavior only seems to work in the internal data structure when the checkbox is explicitly unchecked.

### Environment (_component version number, Browser (including version), operating system, hardware, etc_):
Any

### Code examples help us better understand the issue - follow the appropriate codepen for the component by going to https://predix-ui.com, finding the component in question, and clicking on the pencil icon under the demo.
All CodePens for data-table are currently failing, but it's easy enough to replicate in your local using the first table in demo.html within the repo.

### Upon resolution, please follow up here:
https://forum.predix.io/questions/17483/px-data-table-setting-of-default-columns.html

**Comment by mdwragg** [comment]
@randyaskin fixed in 7f1b7db unit tests failed for hide/show column even though behaviour looked OK. Needs checking though before we merge this.

**Comment by mdwragg** [comment]
Closing due to age and release of https://www.predix-ui.com/#/elements/data-grid/px-data-grid
