### ISSUE TITLE
Issue in saving and retaining px-data-table column sort property

### ISSUE THREAD

**Issue by DipenV** [predixdesignsystem/px-data-table#98]
Hi,

We have a usecase where we need to sort the px-data-table column and save the sorted state, so that next time or after reload when the application loads it should display the same sorted data using px-data-table without any further clicks.

Currently we found within px-data-table-column we can use sortable sort-function-name for custom sort but does not retain the last sorted state after reload and need to mandatory click on column again for sorting.

So is there any property which holds the column sort property or any other way to do the same without clicking the column?

**Comment by randyaskin** [comment]
No, px-data-table doesn't currently have a way of loading with a sort state applied. The default behavior is just to display the data in whatever order you pass it in the table-data property.

**Comment by inaw-tihor** [comment]
Hi,
Is the team planning to support the ability to load with a sort state applied.

**Comment by mdwragg** [comment]
Closing due to age and release of https://www.predix-ui.com/#/elements/data-grid/px-data-grid
